[[main]]
  name = "Setup"
  weight = 1
  identifier = "setup"

[[main]]
  name = "Software Overview"
  url = "setup/"
  weight = 1
  parent = "setup"

[[main]]
  name = "R"
  url = "setup/r/"
  weight = 2
  parent = "setup"

[[main]]
  name = "RStudio"
  url = "setup/RStudio/"
  weight = 3
  parent = "setup"
  
[[main]]
  name = "FinBIF R package"
  url = "setup/finbif/"
  weight = 4
  parent = "setup"
  
[[main]]
  name = "Access Token"
  url = "setup/access-token/"
  weight = 5
  parent = "setup"

[[main]]
  name = "Tutorials"
  weight = 2
  identifier = "tutorials"

[[main]]
  name = "Tutorials Overview"
  url = "tutorials/"
  weight = 1
  parent = "tutorials"

[[main]]
  identifier = "Using the FinBIF R package - tutorial"
  name = "Using the FinBIF R package"
  url = "tutorials/finbif/"
  weight = 2
  parent = "tutorials"

[[main]]
  identifier = "Building an SDM - tutorial"
  name = "Building an SDM"
  url = "tutorials/modelling/"
  weight = 3
  parent = "tutorials"

[[main]]
  pre = "<i class=\"fas fa-tv fa-lg\"></i>"
  name = ""
  weight = 3
  identifier = "slides"

[[main]]
  identifier = "Using the FinBIF R package - presentation"
  name = "Using the FinBIF R package"
  url = "slides/finbif/"
  weight = 1
  parent = "slides"

[[main]]
  pre = "<i class=\"fas fa-book-open fa-lg\"></i>"
  name = ""
  weight = 4
  identifier = "docs"

[[main]]
  name = "Current"
  url = "https://luomus.github.io/finbif/"
  weight = 1
  parent = "docs"

[[main]]
  name = "Development"
  url = "https://finbif-docs-dev.netlify.com/"
  weight = 2
  parent = "docs"

[[main]]
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  name = ""
  url = "https://github.com/luomus/finbif/"
  weight = 5
  identifier = "github"

