# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_night: dark
  font: classic
  font_size: L

# SEO

marketing:
  seo:
    site_type: Project
    org_name: 'LUOMUS - Finnish Museum of Natural History'
    description: 'Workshop on using the FinBIF R package'

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '&copy; {year} LUOMUS - Finnish Museum of Natural History'
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/luomus/finbif-workshop'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
