theme = "dark"

day_night = false

font = "classic"

font_size = "L"

site_type = "Project"

org_name = "LUOMUS - Finnish Museum of Natural History"

description = "Workshop on using the FinBIF R package"

highlight = true
highlight_languages = ["r"]
highlight_style = "atom-one-dark-reasonable"

math = true

diagram = true

privacy_pack = true

edit_page = {repo_url = "", content_dir = "", repo_branch = "master", editable = {docs = false, page = false, post = false}}

email = "willi@mmorris.email"
phone = ""

directions = ""

office_hours = ""

appointment_url = ""

contact_links = []

sharing_image = ""

twitter = ""

date_format = "Jan 2, 2006"
time_format = "3:04 PM"

address_format = "en-us"

main_menu = {align = "l", show_logo = true}

reading_time = false

section_pager = false

docs_section_pager = true

sharing = false

link_authors = false

plugins_js  = []

[avatar]
  gravatar = false
  shape = "circle"

[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

[publications]
  date_format = "January 2006"
  citation_style = "apa"

[projects]
  post_view = 2
  publication_view = 2
  talk_view = 2

[comments]
  engine = 0
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  [comments.disqus]
    shortname = ""
    show_count = true

  [comments.commento]
    url = ""

[search]
  engine = 1

  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

[map]
  engine = 0
  api_key = ""
  zoom = 15

[marketing]
  google_analytics = ""
  google_tag_manager = ""
